// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace Completed
{
    
	public abstract class Strategy
	{
        public int mode; //0 = PvP, 1 = PvE, 2 = EvE
        public List<Enemy> enemy0;
        public List<Enemy> enemy1;
    

		abstract public Vector3[] returnMove(Enemy enemy);
		abstract public Vector3[] getMoveList(Enemy enemy);
		abstract public int evaluateMoveUtility(String move);
		abstract public Vector3[] returnMoves(List<Enemy> enemies);
		abstract public int evaluateDamage(List<Player> players, Enemy enemy);
	}
}

