// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Completed
{
	public abstract class Strategy
	{
		abstract public int[] returnMove(Enemy enemy);
		abstract public int[][] getMoveList(Enemy enemy);
		abstract public int evaluateMoveUtility(String move);
		abstract public int[][] returnMoves(List<Enemy> enemies);
		abstract public int evaluateDamage(List<Player> players, Enemy enemy);
	}
}

