// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using Completed;
using System;

public class AttackFirst : AIBase { //this agent will look for the lowest health agent it can attack; if not, it moves 
	public override void onTurn()
	{
		base.onTurn();
		foreach(Enemy e in self) {
			Vector3 cur = e.currentPos;
			MovingObject attacked = null;
			foreach (MovingObject obj in other)
			{
				bool xComparison = Mathf.Abs(obj.transform.position.x - cur.x) < float.Epsilon;
				bool yComparison = Mathf.Abs(obj.transform.position.y - cur.y) < float.Epsilon;
				if (xComparison && yComparison)
				{
					if (attacked == null) {
						attacked = obj;
					}
					else {
						if (obj.health < attacked.health) {
							attacked = obj;
						}
				}
			   }
			}
			if (attacked) {
				actions.Add(new AIAction(e, AIAction.Actions.Attack, attacked.transform.position));
			}
			else {
				actions.Add(new AIAction(e, AIAction.Actions.Move, cur + new Vector3(1, 1, 0)));
			}
		}
	}
}
